version: "3.9"

services:
  app:
    image: python:3.9-slim
    container_name: fastapi_app
    working_dir: /app
    volumes:
      - ./app:/app
      - ./media:/app/media
      - ./data:/app/data
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_FILE_PATH=/app/data/plan_combined.json
    depends_on:
      - media_service

  media_service:
    image: nginx:latest
    container_name: media_service
    volumes:
      - ./media:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
