"""Init tables

Revision ID: 7c2e3099643b
Revises:
Create Date: 2025-03-11 14:54:28.067272

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c2e3099643b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'buildings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('address', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'room_types',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('type_name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('type_name'),
    )
    op.create_table(
        'floors',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('building_id', sa.UUID(), nullable=False),
        sa.Column('floor_number', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'rooms',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('floor_id', sa.UUID(), nullable=False),
        sa.Column('room_number', sa.String(length=50), nullable=False),
        sa.Column('type_id', sa.UUID(), nullable=True),
        sa.Column('x', sa.Float(), nullable=False),
        sa.Column('y', sa.Float(), nullable=False),
        sa.Column('width', sa.Float(), nullable=False),
        sa.Column('height', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['type_id'], ['room_types.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('room_number'),
    )
    op.create_table(
        'doors',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('room_id', sa.UUID(), nullable=False),
        sa.Column('x', sa.Float(), nullable=False),
        sa.Column('y', sa.Float(), nullable=False),
        sa.Column('width', sa.Float(), nullable=False),
        sa.Column('height', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'connections',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('door_from', sa.UUID(), nullable=False),
        sa.Column('door_to', sa.UUID(), nullable=False),
        sa.Column('distance', sa.Float(), nullable=False),
        sa.Column('estimated_time', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['door_from'], ['doors.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['door_to'], ['doors.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    op.drop_table('doors')
    op.drop_table('rooms')
    op.drop_table('floors')
    op.drop_table('room_types')
    op.drop_table('buildings')
    # ### end Alembic commands ###
