name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

      - name: Ensure Directory on Server
        run: |
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p /var/www/utmn-map/backend"

      - name: Deploy Code
        run: |
          scp -i /tmp/ssh_key -o StrictHostKeyChecking=no -r ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/utmn-map/backend

      - name: Restart Backend Service
        run: |
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo systemctl restart utmn-map-backend"
